/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CodeNexus {
        "css": string;
        /**
          * The length of time to debounce updates to the iframe
         */
        "debounceTime": number;
        /**
          * Hides the live editor containers
         */
        "hideEditors": boolean;
        "html": string;
        "javascript": string;
    }
    interface NexusPanel {
    }
}
declare global {
    interface HTMLCodeNexusElement extends Components.CodeNexus, HTMLStencilElement {
    }
    var HTMLCodeNexusElement: {
        prototype: HTMLCodeNexusElement;
        new (): HTMLCodeNexusElement;
    };
    interface HTMLNexusPanelElement extends Components.NexusPanel, HTMLStencilElement {
    }
    var HTMLNexusPanelElement: {
        prototype: HTMLNexusPanelElement;
        new (): HTMLNexusPanelElement;
    };
    interface HTMLElementTagNameMap {
        "code-nexus": HTMLCodeNexusElement;
        "nexus-panel": HTMLNexusPanelElement;
    }
}
declare namespace LocalJSX {
    interface CodeNexus {
        "css"?: string;
        /**
          * The length of time to debounce updates to the iframe
         */
        "debounceTime"?: number;
        /**
          * Hides the live editor containers
         */
        "hideEditors"?: boolean;
        "html"?: string;
        "javascript"?: string;
    }
    interface NexusPanel {
    }
    interface IntrinsicElements {
        "code-nexus": CodeNexus;
        "nexus-panel": NexusPanel;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "code-nexus": LocalJSX.CodeNexus & JSXBase.HTMLAttributes<HTMLCodeNexusElement>;
            "nexus-panel": LocalJSX.NexusPanel & JSXBase.HTMLAttributes<HTMLNexusPanelElement>;
        }
    }
}
