/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Colors } from "./themes/theme";
import { FormattingOptions } from "./extensions/formatting-extension";
import { Content } from "./components/code-nexus/code-nexus-utils";
export { Colors } from "./themes/theme";
export { FormattingOptions } from "./extensions/formatting-extension";
export { Content } from "./components/code-nexus/code-nexus-utils";
export namespace Components {
    interface CodeNexus {
        "css": string;
        /**
          * The length of time to debounce updates to the iframe
         */
        "debounceTime": number;
        /**
          * Enables code formatting functionality
         */
        "enableFormatting": boolean;
        /**
          * Ability to load example/starter templates
         */
        "enableTemplates": boolean;
        /**
          * Format all code sections
         */
        "formatAll": () => Promise<void>;
        /**
          * Format CSS code
         */
        "formatCss": () => Promise<void>;
        /**
          * Format HTML code
         */
        "formatHtml": () => Promise<void>;
        /**
          * Format JavaScript code
         */
        "formatJs": () => Promise<void>;
        /**
          * Options for code formatting
         */
        "formattingOptions": FormattingOptions;
        /**
          * Hides the live editor containers
         */
        "hideEditors": boolean;
        "html": string;
        "javascript": string;
        /**
          * Load a template into the editor
          * @param template The template object containing html, css, and javascript content
         */
        "loadTemplate": (template: { html: string; css: string; javascript: string; }) => Promise<void>;
        /**
          * Show formatting buttons in the UI
         */
        "showFormattingButtons": boolean;
        /**
          * Switches from split view to a tabbed view
         */
        "tabbed": boolean;
        /**
          * Custom starter templates for quick loading
         */
        "templates": { name: string; html: string; css: string; javascript: string }[];
        "theme": {
    colors: Colors;
    dark: boolean;
  };
    }
    interface NexusPanel {
        "content": string;
        /**
          * Copy button success timeout in ms
         */
        "copySuccessTimeout": number;
        /**
          * Whether to enable syntax highlighting
         */
        "enableSyntaxHighlighting": boolean;
        "panelName": string;
        "readonly": boolean;
        /**
          * Whether to show the copy button
         */
        "showCopyButton": boolean;
        /**
          * Whether to show line numbers
         */
        "showLineNumbers": boolean;
        "theme": {
    colors: Colors;
    dark: boolean;
  };
        "type": Content;
    }
    interface NexusSnippet {
        /**
          * The content inside the snippet (inline code)
         */
        "content": string;
        /**
          * Theme configuration
         */
        "theme": {
    colors: Colors;
    dark: boolean;
  };
        /**
          * The type of code (for syntax highlighting)
         */
        "type": 'js' | 'html' | 'css';
    }
    interface NexusTab {
        "active": boolean;
        /**
          * Whether the tab is disabled
         */
        "disabled": boolean;
        /**
          * Optional icon to display in the tab
         */
        "icon"?: string;
        "onDark": boolean;
        /**
          * Tooltip text for the tab
         */
        "tooltip"?: string;
    }
}
export interface CodeNexusCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCodeNexusElement;
}
export interface NexusPanelCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNexusPanelElement;
}
declare global {
    interface HTMLCodeNexusElementEventMap {
        "contentChange": {
    html: string;
    css: string;
    javascript: string;
  };
    }
    interface HTMLCodeNexusElement extends Components.CodeNexus, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCodeNexusElementEventMap>(type: K, listener: (this: HTMLCodeNexusElement, ev: CodeNexusCustomEvent<HTMLCodeNexusElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCodeNexusElementEventMap>(type: K, listener: (this: HTMLCodeNexusElement, ev: CodeNexusCustomEvent<HTMLCodeNexusElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCodeNexusElement: {
        prototype: HTMLCodeNexusElement;
        new (): HTMLCodeNexusElement;
    };
    interface HTMLNexusPanelElementEventMap {
        "panelContentChange": string;
    }
    interface HTMLNexusPanelElement extends Components.NexusPanel, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNexusPanelElementEventMap>(type: K, listener: (this: HTMLNexusPanelElement, ev: NexusPanelCustomEvent<HTMLNexusPanelElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNexusPanelElementEventMap>(type: K, listener: (this: HTMLNexusPanelElement, ev: NexusPanelCustomEvent<HTMLNexusPanelElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNexusPanelElement: {
        prototype: HTMLNexusPanelElement;
        new (): HTMLNexusPanelElement;
    };
    interface HTMLNexusSnippetElement extends Components.NexusSnippet, HTMLStencilElement {
    }
    var HTMLNexusSnippetElement: {
        prototype: HTMLNexusSnippetElement;
        new (): HTMLNexusSnippetElement;
    };
    interface HTMLNexusTabElement extends Components.NexusTab, HTMLStencilElement {
    }
    var HTMLNexusTabElement: {
        prototype: HTMLNexusTabElement;
        new (): HTMLNexusTabElement;
    };
    interface HTMLElementTagNameMap {
        "code-nexus": HTMLCodeNexusElement;
        "nexus-panel": HTMLNexusPanelElement;
        "nexus-snippet": HTMLNexusSnippetElement;
        "nexus-tab": HTMLNexusTabElement;
    }
}
declare namespace LocalJSX {
    interface CodeNexus {
        "css"?: string;
        /**
          * The length of time to debounce updates to the iframe
         */
        "debounceTime"?: number;
        /**
          * Enables code formatting functionality
         */
        "enableFormatting"?: boolean;
        /**
          * Ability to load example/starter templates
         */
        "enableTemplates"?: boolean;
        /**
          * Options for code formatting
         */
        "formattingOptions"?: FormattingOptions;
        /**
          * Hides the live editor containers
         */
        "hideEditors"?: boolean;
        "html"?: string;
        "javascript"?: string;
        /**
          * Event emitted when any editor content changes
         */
        "onContentChange"?: (event: CodeNexusCustomEvent<{
    html: string;
    css: string;
    javascript: string;
  }>) => void;
        /**
          * Show formatting buttons in the UI
         */
        "showFormattingButtons"?: boolean;
        /**
          * Switches from split view to a tabbed view
         */
        "tabbed"?: boolean;
        /**
          * Custom starter templates for quick loading
         */
        "templates"?: { name: string; html: string; css: string; javascript: string }[];
        "theme"?: {
    colors: Colors;
    dark: boolean;
  };
    }
    interface NexusPanel {
        "content"?: string;
        /**
          * Copy button success timeout in ms
         */
        "copySuccessTimeout"?: number;
        /**
          * Whether to enable syntax highlighting
         */
        "enableSyntaxHighlighting"?: boolean;
        /**
          * Event emitted when content changes
         */
        "onPanelContentChange"?: (event: NexusPanelCustomEvent<string>) => void;
        "panelName"?: string;
        "readonly"?: boolean;
        /**
          * Whether to show the copy button
         */
        "showCopyButton"?: boolean;
        /**
          * Whether to show line numbers
         */
        "showLineNumbers"?: boolean;
        "theme"?: {
    colors: Colors;
    dark: boolean;
  };
        "type"?: Content;
    }
    interface NexusSnippet {
        /**
          * The content inside the snippet (inline code)
         */
        "content"?: string;
        /**
          * Theme configuration
         */
        "theme"?: {
    colors: Colors;
    dark: boolean;
  };
        /**
          * The type of code (for syntax highlighting)
         */
        "type"?: 'js' | 'html' | 'css';
    }
    interface NexusTab {
        "active"?: boolean;
        /**
          * Whether the tab is disabled
         */
        "disabled"?: boolean;
        /**
          * Optional icon to display in the tab
         */
        "icon"?: string;
        "onDark"?: boolean;
        /**
          * Tooltip text for the tab
         */
        "tooltip"?: string;
    }
    interface IntrinsicElements {
        "code-nexus": CodeNexus;
        "nexus-panel": NexusPanel;
        "nexus-snippet": NexusSnippet;
        "nexus-tab": NexusTab;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "code-nexus": LocalJSX.CodeNexus & JSXBase.HTMLAttributes<HTMLCodeNexusElement>;
            "nexus-panel": LocalJSX.NexusPanel & JSXBase.HTMLAttributes<HTMLNexusPanelElement>;
            "nexus-snippet": LocalJSX.NexusSnippet & JSXBase.HTMLAttributes<HTMLNexusSnippetElement>;
            "nexus-tab": LocalJSX.NexusTab & JSXBase.HTMLAttributes<HTMLNexusTabElement>;
        }
    }
}
