/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Colors } from "./themes/theme";
import { Content } from "./components/code-nexus/code-nexus-utils";
export { Colors } from "./themes/theme";
export { Content } from "./components/code-nexus/code-nexus-utils";
export namespace Components {
    interface CodeNexus {
        "css": string;
        /**
          * The length of time to debounce updates to the iframe
         */
        "debounceTime": number;
        /**
          * Hides the live editor containers
         */
        "hideEditors": boolean;
        "html": string;
        "javascript": string;
        /**
          * Switches from split view to a tabbed view
         */
        "tabbed": boolean;
        "theme": {
    colors: Colors;
    dark: boolean;
  };
    }
    interface NexusPanel {
        "content": string;
        "panelName": string;
        "theme": {
    colors: Colors;
    dark: boolean;
  };
        "type": Content;
    }
    interface NexusTab {
        "active": boolean;
        "onDark": boolean;
    }
}
declare global {
    interface HTMLCodeNexusElement extends Components.CodeNexus, HTMLStencilElement {
    }
    var HTMLCodeNexusElement: {
        prototype: HTMLCodeNexusElement;
        new (): HTMLCodeNexusElement;
    };
    interface HTMLNexusPanelElement extends Components.NexusPanel, HTMLStencilElement {
    }
    var HTMLNexusPanelElement: {
        prototype: HTMLNexusPanelElement;
        new (): HTMLNexusPanelElement;
    };
    interface HTMLNexusTabElement extends Components.NexusTab, HTMLStencilElement {
    }
    var HTMLNexusTabElement: {
        prototype: HTMLNexusTabElement;
        new (): HTMLNexusTabElement;
    };
    interface HTMLElementTagNameMap {
        "code-nexus": HTMLCodeNexusElement;
        "nexus-panel": HTMLNexusPanelElement;
        "nexus-tab": HTMLNexusTabElement;
    }
}
declare namespace LocalJSX {
    interface CodeNexus {
        "css"?: string;
        /**
          * The length of time to debounce updates to the iframe
         */
        "debounceTime"?: number;
        /**
          * Hides the live editor containers
         */
        "hideEditors"?: boolean;
        "html"?: string;
        "javascript"?: string;
        /**
          * Switches from split view to a tabbed view
         */
        "tabbed"?: boolean;
        "theme"?: {
    colors: Colors;
    dark: boolean;
  };
    }
    interface NexusPanel {
        "content"?: string;
        "panelName"?: string;
        "theme"?: {
    colors: Colors;
    dark: boolean;
  };
        "type"?: Content;
    }
    interface NexusTab {
        "active"?: boolean;
        "onDark"?: boolean;
    }
    interface IntrinsicElements {
        "code-nexus": CodeNexus;
        "nexus-panel": NexusPanel;
        "nexus-tab": NexusTab;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "code-nexus": LocalJSX.CodeNexus & JSXBase.HTMLAttributes<HTMLCodeNexusElement>;
            "nexus-panel": LocalJSX.NexusPanel & JSXBase.HTMLAttributes<HTMLNexusPanelElement>;
            "nexus-tab": LocalJSX.NexusTab & JSXBase.HTMLAttributes<HTMLNexusTabElement>;
        }
    }
}
