import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import { SpeedInsights } from "@vercel/speed-insights/next"


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <SpeedInsights></SpeedInsights>
          <div className="app-background absolute bg-slate-300 w-full h-full top-0 left-0 opacity-40"></div>
          {children}
        </Providers>
      </body>
    </html>
  );
}
